# Generated by Django 4.2.7 on 2024-02-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('rtsp_status', models.CharField(blank=True, max_length=10, null=True)),
                ('rtsp_message', models.CharField(blank=True, max_length=255, null=True)),
                ('rtsp_frame', models.ImageField(default='default.png', upload_to='images/health/')),
                ('helmet', models.BooleanField(default=False)),
                ('vest', models.BooleanField(default=False)),
                ('polygons', models.TextField(blank=True, null=True)),
                ('email_alert', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
            },
        ),
    ]
