# Generated by Django 4.2.7 on 2024-02-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('incident_image', models.ImageField(default='default.png', upload_to='images/incident/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.camera')),
                ('employee', models.ManyToManyField(blank=True, to='home.employee')),
            ],
            options={
                'verbose_name': 'IncidentLog',
                'verbose_name_plural': 'IncidentLogs',
            },
        ),
    ]
