# Generated by Django 5.0.2 on 2024-02-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_camera_rtsp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='rtsp_frame',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
