# Generated by Django 5.0.2 on 2024-02-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_camera_rtsp_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='rtsp_frame',
            field=models.ImageField(default='default.jpeg', upload_to='status/'),
        ),
    ]
