# Generated by Django 5.0.2 on 2024-02-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_camera_rtsp_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='rtsp_frame',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='status/'),
        ),
    ]
