# Generated by Django 5.0.2 on 2024-02-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_camera_rtsp_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='incident_image',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default=None, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='video_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
