# Generated by Django 5.0.2 on 2024-02-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_employee_id_remove_incident_incident_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='employee',
        ),
        migrations.AddField(
            model_name='incident',
            name='employee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
